version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    links:
      - postgres
    depends_on:
      - postgres

  telebot:
    container_name: telebot
    build:
      context: ./telebot
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "40:40"
    links:
      - api
    depends_on:
      - api

volumes:
  postgres_data: